import type { NextPage } from 'next'
import Head from 'next/head'
import { Accordion } from '../src'
import { Slider } from '../src'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
        <h2 className="text-xl text-gray-600">
          Accordion
        </h2>
          <Accordion.Root type="single" collapsible>
            <Accordion.Item value="item-1">
              <Accordion.Header>
                <Accordion.Trigger>
                  Is it accessible?
                </Accordion.Trigger>
              </Accordion.Header>
              <Accordion.Content className="text-blue-300">
                Yes. It adheres to the WAI-ARAI design pattern.
              </Accordion.Content>
            </Accordion.Item>
            <Accordion.Item value="item-2">
              <Accordion.Header>
                <Accordion.Trigger>
                  Is it accessible?
                </Accordion.Trigger>
              </Accordion.Header>
              <Accordion.Content>
                Yes. It adheres to the WAI-ARAI design pattern.
              </Accordion.Content>
            </Accordion.Item>
          </Accordion.Root>
        </div>
        <div>
          <h2 className="text-xl text-gray-600">
            Slider
          </h2>
          <Slider.Root className='w-[400px]'>
            <Slider.Track>
              <Slider.Range />
            </Slider.Track>
            <Slider.Thumb />
          </Slider.Root>
          <Slider.Root orientation='vertical'>
            <Slider.Track>
              <Slider.Range />
            </Slider.Track>
            <Slider.Thumb />
          </Slider.Root>
        </div>
      </main>
    </div>
  )
}

export default Home