import type { NextPage } from 'next'
import Head from 'next/head'
import { Accordion, Slider, Switch, Tabs, Dialog, Tooltip, Popover, Hovercard } from '../src'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-5xl mx-auto'>
        <Block title="Accordion">
          <Accordion.Root type="single" collapsible>
            <Accordion.Item value="item-1">
              <Accordion.Header>
                <Accordion.Trigger>
                  Is it accessible?
                </Accordion.Trigger>
              </Accordion.Header>
              <Accordion.Content className="text-primary-300">
                Yes. It adheres to the WAI-ARAI design pattern.
              </Accordion.Content>
            </Accordion.Item>
            <Accordion.Item value="item-2">
              <Accordion.Header>
                <Accordion.Trigger>
                  Is it accessible?
                </Accordion.Trigger>
              </Accordion.Header>
              <Accordion.Content>
                Yes. It adheres to the WAI-ARAI design pattern.
              </Accordion.Content>
            </Accordion.Item>
          </Accordion.Root>
        </Block>

        <Block title="Slider">
          <Slider.Root tw="text-gray-400" className='w-[400px]'>
            <Slider.Track>
              <Slider.Range />
            </Slider.Track>
            <Slider.Thumb />
          </Slider.Root>
        </Block>

        <Block title="Slider vertical">
          <Slider.Root orientation='vertical'>
            <Slider.Track>
              <Slider.Range />
            </Slider.Track>
            <Slider.Thumb />
          </Slider.Root>
        </Block>

        <Block title="Switch">
          <Switch.Root defaultChecked={true}>
            <Switch.Thumb />
          </Switch.Root>
        </Block>

        <Block title="Tabs">
          <Tabs.Root defaultValue='tab1'>
            <Tabs.List>
              <Tabs.Trigger value='tab1'>Tab 1</Tabs.Trigger>
              <Tabs.Trigger value='tab2'>Tab 2</Tabs.Trigger>
            </Tabs.List>
            <Tabs.Content value='tab1'>Tab Content 1</Tabs.Content>
            <Tabs.Content value='tab2'>Tab Content 2</Tabs.Content>
          </Tabs.Root>
        </Block>

        <Block title="Dialog">
          <Dialog.Root >
            <Dialog.Trigger>
              Dialog
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay />
              <Dialog.Content>
                <Dialog.Title>
                  Dialog Title
                </Dialog.Title>
                <Dialog.Description>
                  Dialog Description
                </Dialog.Description>
                <Dialog.Close>Close</Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root>
        </Block>

        <Block title="Tooltip">
          <Tooltip.Root>
            <Tooltip.Trigger>Test</Tooltip.Trigger>
            <Tooltip.Content>
              <Tooltip.Arrow />
              Tooltip content
            </Tooltip.Content>
          </Tooltip.Root>
        </Block>

        <Block title="Popover">
          <Popover.Root>
            <Popover.Trigger>Popover</Popover.Trigger>
            <Popover.Content>
              <Popover.Arrow />
              Popover content
            </Popover.Content>
          </Popover.Root>
        </Block>

        <Block title="Hover Card">
          <Hovercard.Root>
            <Hovercard.Trigger>Hovercard</Hovercard.Trigger>
            <Hovercard.Content>
              <Hovercard.Arrow />
              Hovercard content
            </Hovercard.Content>
          </Hovercard.Root>
        </Block>
      </main>
    </div>
  )
}

type BlockProps = {
  title: string;
}

const Block: React.FC<BlockProps> = ({title, children}) => {
  return (
    <div className=' my-14'>
      <h2 className="text-xl text-gray-800">
        {title}
      </h2>
      <div className="w-full h-px bg-gray-200 mt-2 mb-6" />
      <div className="p-4 bg-gray-50 rounded-lg">
        {children}
      </div>
    </div>
  )
}

export default Home