import type { NextPage } from 'next'
import Head from 'next/head'
import { Accordion } from 'component-library'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Accordion.Root type="single" collapsible>
          <Accordion.Item value="item-1">
            <Accordion.Header>
              <Accordion.Trigger>
                Is it accessible?
              </Accordion.Trigger>
            </Accordion.Header>
            <Accordion.Content>
              Yes. It adheres to the WAI-ARAI design pattern.
            </Accordion.Content>
          </Accordion.Item>
          <Accordion.Item value="item-2">
            <Accordion.Header>
              <Accordion.Trigger>
                Is it accessible?
              </Accordion.Trigger>
            </Accordion.Header>
            <Accordion.Content>
              Yes. It adheres to the WAI-ARAI design pattern.
            </Accordion.Content>
          </Accordion.Item>
        </Accordion.Root>
      </main>
    </div>
  )
}

export default Home